from typing import List
from enum import Enum
from pydantic import BaseModel, Field

class LoveType(str, Enum):
    BELONG = "BELONG"
    FIRE = "FIRE"
    SPARK = "SPARK"
    CARE = "CARE"
    SELF = "SELF"
    BUILD = "BUILD"
    GROW = "GROW"
    BEYOND = "BEYOND"
    GRACE = "GRACE"

class RelationalNeed(str, Enum):
    CONNECTION = "CONNECTION"
    INTIMACY = "INTIMACY"
    UNDERSTANDING = "UNDERSTANDING"
    ACCEPTANCE_AND_FORGIVENESS = "ACCEPTANCE_AND_FORGIVENESS"
    TRUST_AND_SAFETY = "TRUST_AND_SAFETY"
    SUPPORT = "SUPPORT"
    BALANCE_AND_FAIRNESS = "BALANCE_AND_FAIRNESS"
    COMMUNICATION = "COMMUNICATION"
    PLAY_AND_JOY = "PLAY_AND_JOY"
    GROWTH = "GROWTH"
    GRATITUDE_AND_APPRECIATION = "GRATITUDE_AND_APPRECIATION"
    PRESENCE_AND_QUALITY_TIME = "PRESENCE_AND_QUALITY_TIME"
    SPACE = "SPACE"

class RitualTone(str, Enum):
    WARM = "WARM"
    PLAYFUL = "PLAYFUL"
    INTIMATE = "INTIMATE"
    REFLECTIVE = "REFLECTIVE"
    CALM = "CALM"
    ADVENTUROUS = "ADVENTUROUS"
    ENERGETIC = "ENERGETIC"
    HEALING = "HEALING"
    SACRED = "SACRED"

class TimeTaken(str, Enum):
    MOMENT = "MOMENT"
    SHORT = "SHORT"
    MEDIUM = "MEDIUM"
    LONG = "LONG"
    EXTENDED = "EXTENDED"
    FLEXIBLE = "FLEXIBLE"

class RitualDetailsResponse(BaseModel):
    """Structured ritual details generated by the LLM for the Loving App."""
    tagLine: str = Field(
        description=(
            "A short, emotionally resonant one-line phrase that captures the essence of the ritual. It should feel inviting and memorable, without sounding poetic or abstract. Aim for clarity and warmth."
        )
    )

    description: str = Field(
        description=(
            "A concise overview of what the ritual involves and the emotional intention behind it. Explain the purpose in plain, grounded language and set expectations for what the user will experience. Avoid metaphor-heavy or overly spiritual language."
        )
    )

    steps: List[str] = Field(
        description=(
            "A clear, chronological list of steps guiding the ritual. Each step should be practical, emotionally gentle, and easy to follow in daily life. Steps should be numbered, written in a warm, invitational tone and may begin with a short action-oriented title."
        )
    )

    howItHelps: str = Field(
        description=(
            "An empathetic explanation of the emotional or relational shift this ritual supports. Focus on how the practice helps participants feel or relate differently afterward. Write in natural language (2–4 sentences), grounded in lived emotional experience."
        )
    )

    loveTypes: List[LoveType] = Field(
        description=(
            "The primary love types this ritual expresses or strengthens. Select 1–3 values that best represent the ritual’s core emotional theme. Choose conservatively rather than exhaustively."
        )
    )

    relationalNeeds: List[RelationalNeed] = Field(
        description=(
            "The main relational or emotional needs this ritual is designed to support. Select 1–3 values that are most central to the ritual’s purpose, based on the user’s likely emotional context."
        )
    )

    ritualTones: List[RitualTone] = Field(
        description=(
            "The emotional atmosphere or felt quality of the ritual. Select 1–3 tones that best describe how the ritual feels to experience, rather than how it sounds when described."
        )
    )

    timeTaken: TimeTaken = Field(
        description=(
            "An estimate of how long the ritual typically takes to complete. Choose the category that best reflects real-world use rather than the fastest possible completion."
        )
    )

    semanticSummary: str = Field(
        description=(
            "A brief, compassionate summary (2–4 sentences) describing when this ritual is most helpful, what emotional state it supports, and what kind of shift it offers. This should read like guidance from a thoughtful companion, not marketing copy."
        )
    )

class BatchRitualDetailsResponse(BaseModel):
    """Batched structured response for multiple rituals. Each ritual should be completed independently using its corresponding input context."""

    rituals: List[RitualDetailsResponse] = Field(
        description=(
            "A list of fully populated ritual definitions, one per input ritual. Each item must be completed independently using its provided title, description, and tags, without referencing or blending with other rituals in the batch."
        )
    )
