services:
  loving-backend:
    build: .
    ports:
      - "8080:8080"

    environment:
      SPRING_PROFILES_ACTIVE: dev
      AI_OPENAI_API_KEY: ${AI_OPENAI_API_KEY}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SUPABASE_URL: ${SUPABASE_URL}
      LOKI_URL: ${LOKI_URL}
      LOKI_USERNAME: ${LOKI_USERNAME}
      LOKI_API_KEY: ${LOKI_API_KEY}
