services:
  loving-backend:
    build: .
    ports:
      - "8080:8080"

    environment:
      SPRING_PROFILES_ACTIVE: dev
      AI_OPENAI_API_KEY: ${AI_OPENAI_API_KEY}
      DB_URL: ${DB_URL}
      DB_APP_USERNAME: ${DB_APP_USERNAME}
      DB_APP_PASSWORD: ${DB_APP_PASSWORD}
      DB_MIGRATION_USERNAME: ${DB_MIGRATION_USERNAME}
      DB_MIGRATION_PASSWORD: ${DB_MIGRATION_PASSWORD}
      DB_READONLY_USERNAME: ${DB_READONLY_USERNAME}
      DB_READONLY_PASSWORD: ${DB_READONLY_PASSWORD}
      SUPABASE_URL: ${SUPABASE_URL}
      LOKI_URL: ${LOKI_URL}
      LOKI_USERNAME: ${LOKI_USERNAME}
      LOKI_API_KEY: ${LOKI_API_KEY}
