services:
  loving-backend:
    build: .
    ports:
      - "8080:8080"

    volumes:
      - ./certs:/app/certs:ro

    environment:
      SPRING_PROFILES_ACTIVE: prod
      AI_OPENAI_API_KEY: ${AI_OPENAI_API_KEY}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_SSL_CERT_PATH: ${DB_SSL_CERT_PATH:-/app/certs/supabase-ca.crt}
      DB_APP_USERNAME: ${DB_APP_USERNAME}
      DB_APP_PASSWORD: ${DB_APP_PASSWORD}
      DB_MIGRATION_USERNAME: ${DB_MIGRATION_USERNAME}
      DB_MIGRATION_PASSWORD: ${DB_MIGRATION_PASSWORD}
      DB_READONLY_USERNAME: ${DB_READONLY_USERNAME}
      DB_READONLY_PASSWORD: ${DB_READONLY_PASSWORD}
      SUPABASE_URL: ${SUPABASE_URL}
      LOKI_URL: ${LOKI_URL}
      LOKI_USERNAME: ${LOKI_USERNAME}
      LOKI_API_KEY: ${LOKI_API_KEY}
      GRAFANA_PROMETHEUS_URL: ${GRAFANA_PROMETHEUS_URL}
      GRAFANA_PROMETHEUS_USERNAME: ${GRAFANA_PROMETHEUS_USERNAME}
      GRAFANA_PROMETHEUS_API_KEY: ${GRAFANA_PROMETHEUS_API_KEY}
    networks:
      - monitoring

  # Sidecar (Prometheus in Agent Mode)
  prometheus-agent:
    image: prom/prometheus:latest
    command:
      - "--config.file=/app/prometheus/prometheus.yml"
      - "--agent"
      - "--storage.agent.path=/prometheus" # This will now be accepted
      # - "--enable-feature=agent" # This turns off local storage and enables 'pushing'
    volumes:
      - ./src/main/resources/prometheus.yml:/app/prometheus/prometheus.yml
    networks:
      - monitoring
    depends_on:
      - loving-backend
    environment:
      GRAFANA_PROMETHEUS_URL: ${GRAFANA_PROMETHEUS_URL}
      GRAFANA_PROMETHEUS_USERNAME: ${GRAFANA_PROMETHEUS_USERNAME}
      GRAFANA_PROMETHEUS_API_KEY: ${GRAFANA_PROMETHEUS_API_KEY}

networks:
  monitoring:
