spring:
  datasource:
    hikari:
      maximum-pool-size: 8
      minimum-idle: 2
      idle-timeout: 300000                    # 5 min
      leak-detection-threshold: 60000         # 1 min
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 20
          fetch_size: 50
        order_inserts: true
        order_updates: true

ai:
  openai:
    prompts:
      empathetic-chat-response:
        name: empathetic_chat_response
        id: pmpt_69c3d064cc548196a8841243fe7c72fb08967bd5dbf2930f
        version: "3"
      user-context-extraction:
        name: user_context_extraction
        id: pmpt_69c3d10403c4819595deeaa9613bc71b0ba03035b585317a
        version: "2"
      wrap-up-chat-response:
        name: wrap_up_chat_response
        id: pmpt_69c3d1715bdc8193befa9d67d4d06f5c09d22a52153e523b
        version: "2"

management:
  endpoint:
    health:
      show-details: when-authorized
  otlp:
    metrics:
      export:
        enabled: true
  health:
    db:
      enabled: true
