spring:
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 20
          fetch_size: 50
        order_inserts: true
        order_updates: true

ai:
  openai:
    prompts:
      empathetic-chat-response:
        name: empathetic_chat_response
        id: pmpt_699fd785fc34819087b33231cd9060ff0e4ac7e54210cd79
        version: "6"
      user-context-extraction:
        name: user_context_extraction
        id: pmpt_69b0f66d64388195932ce49c40739a240bc30d0d9cfd7126
        version: "1"
      wrap-up-chat-response:
        name: wrap_up_chat_response
        id: pmpt_69b0f97c27a881909324dd324d3882ed0df189ca14cd810f
        version: "2"

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info

  endpoint:
    health:
      show-details: when-authorized
  
  health:
    db:
      enabled: true
