CREATE ROLE loving_migration LOGIN PASSWORD 'strong_password';

GRANT CONNECT ON DATABASE postgres TO loving_migration;
GRANT USAGE, CREATE ON SCHEMA public TO loving_migration;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO loving_migration;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO loving_migration;


CREATE ROLE loving_app LOGIN PASSWORD 'strong_password';

GRANT CONNECT ON DATABASE postgres TO loving_app;
GRANT USAGE ON SCHEMA public TO loving_app;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public
TO loving_app;

GRANT USAGE, SELECT
ON ALL SEQUENCES IN SCHEMA public
TO loving_app;


ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLES TO loving_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT
ON SEQUENCES TO loving_app;


CREATE ROLE loving_readonly LOGIN PASSWORD 'strong_password';

GRANT CONNECT ON DATABASE postgres TO loving_readonly;
GRANT USAGE ON SCHEMA public TO loving_readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO loving_readonly;


REVOKE ALL ON SCHEMA public FROM PUBLIC;
REVOKE ALL ON DATABASE postgres FROM PUBLIC;


SPRING_DATASOURCE_USERNAME = loving_app
SPRING_DATASOURCE_PASSWORD = <secure_password>


SPRING_FLYWAY_USER = loving_migration
SPRING_FLYWAY_PASSWORD = <secure_password>


